---
 - hosts: localhost
   gather_facts: False

   tasks:
     - name: Getting server uptime
       command: 'uptime'
       register: output

     - name: Show output
       debug: var=output.stdout_lines
